In [14]:

import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler

# 1. Create the dataset
data = {
    "Name": ["Aman", "Riya", "Rahul", "Priya", "Aman", "Neha"],
    "Hours_Studied": [2, 5, np.nan, 7, 2, 4],
    "Attendance": [60, 85, 70, np.nan, 60, 90],
    "Gender": ["Male", "Female", "Male", "Female", "Male", "Female"],
    "Marks": [45, 85, 60, 90, 45, np.nan]
}

df = pd.DataFrame(data)

print("1. Original Dataset")
display(df)

# 2. Check missing values
print("2. Missing Values")
print(df.isnull().sum())

# 3. Remove duplicate rows
df = df.drop_duplicates()

# 4. Fill missing numerical values with averages
columns = ["Hours_Studied", "Attendance", "Marks"]

for column in columns:
    df[column] = df[column].fillna(df[column].mean())

print("3. Cleaned Dataset")
display(df)

print("Missing values after cleaning:")
print(df.isnull().sum())

# 5. Encode categorical data
df = pd.get_dummies(df, columns=["Gender"], dtype=int)

# 6. Normalize numerical columns
scaler = MinMaxScaler()
df[columns] = scaler.fit_transform(df[columns])

print("4. Final Processed Dataset")
display(df)

# 7. Explore the dataset
print("5. Dataset Size:")
print(df.shape)

print("6. Summary Statistics:")
display(df.describe())

# 8. Save the final dataset
df.to_csv("cleaned_student_data.csv", index=False)

print("7. Dataset saved successfully!")

1. Original Dataset

    Name  Hours_Studied  Attendance  Gender  Marks
0   Aman            2.0        60.0    Male   45.0
1   Riya            5.0        85.0  Female   85.0
2  Rahul            NaN        70.0    Male   60.0
3  Priya            7.0         NaN  Female   90.0
4   Aman            2.0        60.0    Male   45.0
5   Neha            4.0        90.0  Female    NaN

2. Missing Values
Name             0
Hours_Studied    1
Attendance       1
Gender           0
Marks            1
dtype: int64
3. Cleaned Dataset

    Name  Hours_Studied  Attendance  Gender  Marks
0   Aman            2.0       60.00    Male   45.0
1   Riya            5.0       85.00  Female   85.0
2  Rahul            4.5       70.00    Male   60.0
3  Priya            7.0       76.25  Female   90.0
5   Neha            4.0       90.00  Female   70.0

Missing values after cleaning:
Name             0
Hours_Studied    0
Attendance       0
Gender           0
Marks            0
dtype: int64
4. Final Processed Dataset

    Name  Hours_Studied  Attendance     Marks  Gender_Female  Gender_Male
0   Aman            0.0    0.000000  0.000000              0            1
1   Riya            0.6    0.833333  0.888889              1            0
2  Rahul            0.5    0.333333  0.333333              0            1
3  Priya            1.0    0.541667  1.000000              1            0
5   Neha            0.4    1.000000  0.555556              1            0

5. Dataset Size:
(5, 6)
6. Summary Statistics:

       Hours_Studied  Attendance     Marks  Gender_Female  Gender_Male
count       5.000000    5.000000  5.000000       5.000000     5.000000
mean        0.500000    0.541667  0.555556       0.600000     0.400000
std         0.360555    0.397475  0.408248       0.547723     0.547723
min         0.000000    0.000000  0.000000       0.000000     0.000000
25%         0.400000    0.333333  0.333333       0.000000     0.000000
50%         0.500000    0.541667  0.555556       1.000000     0.000000
75%         0.600000    0.833333  0.888889       1.000000     1.000000
max         1.000000    1.000000  1.000000       1.000000     1.000000

7. Dataset saved successfully!